basePath: /api/v1
definitions:
  models.AssignAdvisorRequest:
    properties:
      advisorUserId:
        description: Kita input User ID Dosen, nanti sistem cari Lecturer ID-nya
        type: string
    type: object
  models.CreateAchievementRequest:
    properties:
      achievementType:
        type: string
      description:
        type: string
      details:
        additionalProperties: true
        type: object
      points:
        type: integer
      tags:
        items:
          type: string
        type: array
      title:
        type: string
    type: object
  models.CreateUserRequest:
    properties:
      email:
        type: string
      fullName:
        type: string
      password:
        type: string
      roleName:
        type: string
      username:
        type: string
    type: object
  models.LecturerProfileRequest:
    properties:
      department:
        type: string
      lecturerId:
        description: NIP
        type: string
    type: object
  models.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  models.StudentProfileRequest:
    properties:
      academicYear:
        type: string
      programStudy:
        type: string
      studentId:
        description: NIM
        type: string
    type: object
  models.UpdateUserRequest:
    properties:
      email:
        type: string
      fullName:
        type: string
      isActive:
        type: boolean
      roleName:
        type: string
    type: object
  utils.JSONResponse:
    properties:
      data: {}
      message:
        type: string
      status:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: support@unair.ac.id
    name: Tim Pengembang
  description: API Server untuk manajemen prestasi mahasiswa, dosen wali, dan admin.
  termsOfService: http://swagger.io/terms/
  title: Sistem Pelaporan Prestasi Mahasiswa API
  version: "1.0"
paths:
  /achievements:
    get:
      responses: {}
      security:
      - BearerAuth: []
      summary: List Achievements
      tags:
      - Achievements
    post:
      parameters:
      - description: Achievement Data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.CreateAchievementRequest'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/utils.JSONResponse'
      security:
      - BearerAuth: []
      summary: Create Achievement Draft
      tags:
      - Achievements
  /achievements/{id}:
    delete:
      responses: {}
      security:
      - BearerAuth: []
      summary: Soft Delete Achievement
      tags:
      - Achievements
    get:
      responses: {}
      security:
      - BearerAuth: []
      summary: Get Achievement Detail
      tags:
      - Achievements
    put:
      parameters:
      - description: Achievement ID
        in: path
        name: id
        required: true
        type: string
      responses: {}
      security:
      - BearerAuth: []
      summary: Update Achievement Draft
      tags:
      - Achievements
  /achievements/{id}/attachments:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: File
        in: formData
        name: attachment
        required: true
        type: file
      responses: {}
      security:
      - BearerAuth: []
      summary: Upload Attachment
      tags:
      - Achievements
  /achievements/{id}/hard:
    delete:
      description: Hapus permanen dari PostgreSQL & MongoDB (Admin Only)
      responses: {}
      security:
      - BearerAuth: []
      summary: Hard Delete Achievement
      tags:
      - Achievements
  /achievements/{id}/reject:
    post:
      responses: {}
      security:
      - BearerAuth: []
      summary: Reject Achievement (Dosen Wali)
      tags:
      - Achievements
  /achievements/{id}/submit:
    post:
      responses: {}
      security:
      - BearerAuth: []
      summary: Submit Achievement
      tags:
      - Achievements
  /achievements/{id}/verify:
    post:
      responses: {}
      security:
      - BearerAuth: []
      summary: Verify Achievement (Dosen Wali)
      tags:
      - Achievements
  /auth/login:
    post:
      consumes:
      - application/json
      description: Masuk menggunakan username dan password untuk mendapatkan token
        JWT
      parameters:
      - description: Credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.JSONResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.JSONResponse'
      summary: Login User
      tags:
      - Auth
  /auth/logout:
    post:
      description: Logout dari sistem (Client harus menghapus token di sisi mereka)
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.JSONResponse'
      security:
      - BearerAuth: []
      summary: Logout User
      tags:
      - Auth
  /auth/profile:
    get:
      consumes:
      - application/json
      description: Mendapatkan data profil user yang sedang login
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.JSONResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.JSONResponse'
      security:
      - BearerAuth: []
      summary: Get User Profile
      tags:
      - Auth
  /reports/statistics:
    get:
      consumes:
      - application/json
      description: Melihat ringkasan data statistik prestasi (Total, by Status, by
        Type)
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.JSONResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.JSONResponse'
      security:
      - BearerAuth: []
      summary: Get Dashboard Statistics
      tags:
      - Reports
  /users:
    get:
      consumes:
      - application/json
      description: Admin melihat semua daftar pengguna (Mahasiswa, Dosen, Admin)
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.JSONResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.JSONResponse'
      security:
      - BearerAuth: []
      summary: List All Users
      tags:
      - Users (Admin)
    post:
      consumes:
      - application/json
      description: Admin membuat akun pengguna baru
      parameters:
      - description: User Data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/utils.JSONResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.JSONResponse'
      security:
      - BearerAuth: []
      summary: Create New User
      tags:
      - Users (Admin)
  /users/{id}:
    delete:
      consumes:
      - application/json
      description: Admin menonaktifkan akun pengguna
      parameters:
      - description: User ID (UUID)
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.JSONResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.JSONResponse'
      security:
      - BearerAuth: []
      summary: Deactivate User (Soft Delete)
      tags:
      - Users (Admin)
    get:
      consumes:
      - application/json
      description: Admin melihat detail data pengguna berdasarkan UUID
      parameters:
      - description: User ID (UUID)
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.JSONResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.JSONResponse'
      security:
      - BearerAuth: []
      summary: Get User By ID
      tags:
      - Users (Admin)
    put:
      consumes:
      - application/json
      description: Admin memperbarui data pengguna
      parameters:
      - description: User ID (UUID)
        in: path
        name: id
        required: true
        type: string
      - description: Update Data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.JSONResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.JSONResponse'
      security:
      - BearerAuth: []
      summary: Update User
      tags:
      - Users (Admin)
  /users/{id}/advisor:
    put:
      consumes:
      - application/json
      description: Menghubungkan mahasiswa dengan dosen walinya
      parameters:
      - description: User ID Mahasiswa (UUID)
        in: path
        name: id
        required: true
        type: string
      - description: User ID Dosen (UUID)
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.AssignAdvisorRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.JSONResponse'
      security:
      - BearerAuth: []
      summary: Assign Advisor to Student
      tags:
      - Users (Admin)
  /users/{id}/lecturer-profile:
    post:
      consumes:
      - application/json
      description: Melengkapi data kepegawaian dosen (NIP, Departemen)
      parameters:
      - description: User ID (UUID)
        in: path
        name: id
        required: true
        type: string
      - description: Lecturer Profile Data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.LecturerProfileRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.JSONResponse'
      security:
      - BearerAuth: []
      summary: Set Lecturer Profile
      tags:
      - Users (Admin)
  /users/{id}/student-profile:
    post:
      consumes:
      - application/json
      description: Melengkapi data akademik mahasiswa (NIM, Prodi, Tahun)
      parameters:
      - description: User ID (UUID)
        in: path
        name: id
        required: true
        type: string
      - description: Student Profile Data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.StudentProfileRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.JSONResponse'
      security:
      - BearerAuth: []
      summary: Set Student Profile
      tags:
      - Users (Admin)
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
